
# Proxy 配置
product_name = "codis-test"
proxy_id = 1

# 对客户端开放端口
proxy_addr = "0.0.0.0:19000"
proxy_admin_addr = "0.0.0.0:11080"

# Dashboard 地址
dashboard_addr = "http://codis-dashboard:18080"

# Etcd 作为协调器
coordinator_name = "etcd"
coordinator_addr = "etcd:2379"

# 连接池配置
backend_primary_parallel = 1
backend_primary_idle_timeout = 30
backend_replica_parallel = 1
backend_replica_idle_timeout = 30

# 会话配置
session_max_timeout = 1800
session_max_bufsize = 131072
session_max_pipeline = 1000