server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  tcp:
    addr: 0.0.0.0:3101
    timeout: 1s
  websocket:
    addr: 0.0.0.0:3102
    timeout: 1s
  gnet:
    addr: 0.0.0.0:3103
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(192.168.152.128:3306)/user_demo?parseTime=True&loc=Local
  redis:
    addr: 192.168.152.128:6379
    password: ""
    read_timeout: 0.2s
    write_timeout: 0.2s
  rabbitmq:
    host: 192.168.152.128
    port: "5672"
    username: admin
    password: myMQ#@g3359Blue#@test.com
    vhost: /